main_app/urls.py
from django.urls import path
from . import views
from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.generic.base import RedirectView

app_name = 'frontend'

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('music/', views.music_index, name='user_index'),
    path('music/all', views.all_index, name='all_index'),
    path('music/create/', views.MusicCreate.as_view(), name='music_create'),
    path('music/<int:pk>/update/', views.MusicUpdate.as_view(), name='music_update'),
    path('music/<int:pk>/delete/', views.MusicDelete.as_view(), name='music_delete'),
    path('music/<int:music_id>/', views.music_detail, name='detail'),
    # adds photo
    path('music/<int:music_id>/add_photo', views.add_photo, name='add_photo'),
    # adds date/way of listen
    path('music/<int:music_id>/add_listen', views.add_listen, name='add_listen'),

    path('accounts/signup/', views.signup, name='signup'),

    #adds favicon 
    path('favicon.ico', RedirectView.as_view(url=staticfiles_storage.url('img/favicon.ico'))),

]

music_memories/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('spotify/', include('spotify.urls')),
]

spotify/urls.py
from django.urls import path
from django.urls.resolvers import URLPattern
from .views import AuthURL, spotify_callback, IsAuthenticated

urlpatterns = [
    path('get-auth-url', AuthURL.as_view()),
    path('redirect', spotify_callback),
    path('is-authenticated', IsAuthenticated.as_view())
]

main_app/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

# Create your models here.

LISTENED = (
    ('C','Casette'),
    ('D','CD'),
    ('L','Live'),
    ('P','Pandora'),
    ('R','Radio'),
    ('S','Spotify'),
)

TYPE = (
    ('A', 'Artist'),
    ('B', 'Album'),
    ('T', 'Track'),
)


class Music(models.Model):
    date_created = models.DateField()
    artist = models.CharField(max_length=100)
    album = models.CharField(max_length=100, blank=True, null=True)
    song = models.CharField(max_length=100, blank=True, null=True)
    genre = models.CharField(max_length=100, blank=True, null=True)
    comments = models.CharField(max_length=1000, blank=True, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    type = models.CharField(
        max_length=1,
        choices=TYPE,
        default=TYPE[2][0],
    )
    spotify_uri = models.CharField(max_length=100, blank=True, null=True)
    spotify_url = models.CharField(max_length=500, blank=True, null=True)

    def __str__(self):
        if (self.song):
            return self.song
        elif (self.album):
            return self.album
        else:
            return self.artist

class Photo(models.Model):
    url = models.CharField(max_length=200)
    music = models.ForeignKey(Music, on_delete=models.CASCADE)

    def __str__(self):
        return f"Photo for music_id: {self.music_id} @{self.url}"


class Listen(models.Model):
    class Meta:
        ordering = ['-date']
    date = models.DateField('listening date')
    listening = models.CharField(
        max_length=1,
        choices=LISTENED,
        default=LISTENED[0][0],
    )

    music = models.ForeignKey(Music, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.get_listening_display()} on {self.date}"

main_app/forms.py
from django.forms import ModelForm
from .models import Listen

class ListenForm(ModelForm):
    class Meta:
        model = Listen
        fields = ['date', 'listening']

        

main_app/views.py
from django.shortcuts import redirect, render
from spotipy.client import Spotify
from .models import Music, Photo
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from .forms import ListenForm
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from dotenv import load_dotenv
import boto3
import uuid
import spotipy
from spotipy.oauth2 import SpotifyClientCredentials, SpotifyOAuth
import os

S3_BASE_URL = 'http://s3.us-east-1.amazonaws.com/'
BUCKET = 'music-memories-p4'

def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

def get_spotify_auth():
    load_dotenv()
    CLIENT_ID = os.environ.get('CLIENT_ID')
    CLIENT_SECRET = os.environ.get('CLIENT_SECRET')
    client_credentials_manager = SpotifyClientCredentials(CLIENT_ID, CLIENT_SECRET)
    sp = spotipy.Spotify(client_credentials_manager=client_credentials_manager)
    return sp

def search_spotify_api(sp, music):
    try:
        if (music.type == 'T'):
            q = music.song
            type = 'track'
        elif (music.type == 'B'):
            q = music.album
            type = 'album'
        else:
            q = music.artist
            type ='artist'

        results = sp.search(q, limit=1, type=type, market='US')
        return results
    except:
        return None

def get_spotify_fields(music):
    sp = get_spotify_auth()

    try:
        if not music.spotify_uri:
            result = search_spotify_api(sp, music)
            if (music.type == "T"):
                music.spotify_uri = result['tracks']['items'][0]['uri']
                music.spotify_url = result['tracks']['items'][0]['external_urls']['spotify']
            elif (music.type == "B"):
                music.spotify_uri = result['albums']['items'][0]['uri']
                music.spotify_uri = result['albums']['items'][0]['external_urls']['spotify']
            else:
                music.spotify_uri = result['artists']['items'][0]['uri']
                music.spotify_uri = result['artists']['items'][0]['external_urls']['spotify']
    except:
        music.spotify_uri = None
        music.spotify_url = None

@login_required
def music_index(request):
    music = Music.objects.filter(user=request.user)
    return render(request, 'music/index.html', {'music': music})

def all_index(request):
    music = Music.objects.all()
    return render(request, 'music/all_index.html', {'music': music})

def add_listen(request, music_id):
    form = ListenForm(request.POST)
    if form.is_valid():
        new_listen = form.save(commit=False)
        new_listen.music_id = music_id
        new_listen.save()
    return redirect('detail', music_id=music_id)

class MusicCreate(LoginRequiredMixin, CreateView):
    model = Music
    fields = ['date_created', 'artist', 'album', 'song', 'genre', 'comments']
    success_url = '/music/'

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

class MusicUpdate(LoginRequiredMixin, UpdateView):
    model = Music
    fields = ['artist', 'album', 'song', 'genre', 'comments']
    success_url = '/music/'

class MusicDelete(LoginRequiredMixin, DeleteView):
    model = Music
    success_url = '/music/'

@login_required
def music_detail(request, music_id):
    music = Music.objects.get(id=music_id)
    listen_form = ListenForm()

    get_spotify_fields(music)

    return render(request, 'music/detail.html', {
        'music': music,
        'listen_form': listen_form,})

def add_photo(request, music_id):
    photo_file = request.FILES.get('photo-file', None)
    if photo_file:
        s3 = boto3.client('s3')
        key = uuid.uuid4().hex[:6] + photo_file.name[photo_file.name.rfind('.'):]
        try:
            s3.upload_fileobj(photo_file, BUCKET, key)
            url = f"{S3_BASE_URL}{BUCKET}/{key}"
            photo = Photo(url=url, music_id=music_id)
            photo.save()
        except Exception as error:
            print('An error occured uploading file to S3')
            print(error)
    return redirect('detail', music_id=music_id)

def signup(request):
  error_message = ''
  if request.method == 'POST':
    # This is how to create a 'user' form object
    # that includes the data from the browser
    form = UserCreationForm(request.POST)
    if form.is_valid():
      # This will add the user to the database
      user = form.save()
      # This is how we log a user in via code
      login(request, user)
      return redirect('user_index')
    else:
      error_message = 'Invalid sign up - try again'
  # A bad POST or a GET request, so render signup.html with an empty form
  form = UserCreationForm()
  context = {'form': form, 'error_message': error_message}
  return render(request, 'registration/signup.html', context)

main_app/templates/music/all_index.html
{% extends 'base.html' %}
{% block content %}

<h1 class="page-title">Browse MusicMemories</h1>
    <div class="cards">
    {% for i in music %}
        <div class="card">
            {% if i.photo_set.all %}
                <img class="card" src="{{ i.photo_set.all.first.url }}">
            {% else %}
                <img class="card" src="../../static/img/Music.png">
            {% endif %}
            <a href="{% url 'detail' i.id %}">
                <div class="card-content">
                    <span class="card-title">{{ i.user }}</span>
                    <p>{{ i.date_created }}</p>
                    <p>Artist: {{ i.artist }}</p>
                    <p>Album: {{ i.album }}</p>
                    <p>Song: {{ i.song }}</p>
                    <p>Genre: {{ i.genre }}</p>
                  
                </div>
            </a>
        </div>
    {% endfor %}
    </div>

{% endblock %}

main_app/templates/music/detail.html
{% extends 'base.html' %}
{% block content %}
<h1 class="page-title">Entry Details</h1>
<div class="row">
    <div class="col s6">
        <div class="card">
            <div class="card-content">
                <span class="card-title">{{ music.date_created }}</span>
                <p>Song: {{ music.song }}</p>
                <p>Album: {{ music.album }}</p>
                <p>Artist: {{ music.artist }}</p>
                <p>Genre: {{ music.genre }}</p>
                <p>Comments: {{ music.comments }}</p>
                {% if music.spotify_url %}
                    <a href="{{ music.spotify_url }}">View on Spotify</a>
                {% endif %}

               
            </div>
            {% if user == music.user %}
            <div class="card-action">
                <a href="{% url 'music_update' music.id%}">Edit</a>
                <a href="{% url 'music_delete' music.id%}">Delete</a>
            </div>
            {% endif %}
        </div>
        
        {% for photo in music.photo_set.all %}
            <img src="{{photo.url}}" alt="{{music.song}}" class="responsive-img card-panel">
        {% empty %}
            <div class="card-panel teal-text center-align">No Memory Images Uploaded</div>
        {% endfor %}
        {% if user == music.user %}
        <form class="card-panel" action="{% url 'add_photo' music.id %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <input type="file" name="photo-file">
            <br>
            <br>
            <input type="submit" class="btn" value="Upload Photo">
        </form>
        {% endif %}

    </div>
<!-- markup for adding way listened -->
    <div class="col s6">
        {% if user == music.user %}
        <form action="{% url 'add_listen' music.id %}" method="POST">
            {% csrf_token %}
            {{ listen_form.as_p }}
            <input type="submit" class="btn" value="Add Way Listened">
        </form>
        {% endif %}
        <table class="striped">
            <thead>
                <tr>
                    <th>Date Listened</th>
                    <th>Way Listened</th>
                </tr>
            </thead>
            <tbody>
                {% for listen in music.listen_set.all %}
                <tr>
                    <td>{{ listen.date }}</td>
                    <td>{{ listen.get_listening_display }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

</div>


<script>
    //Constants
    const dateEl = document.getElementById('id_date');
    const selectEl = document.getElementById('id_listening');

    //Configure the datepicker

    M.Datepicker.init(dateEl, {
        format: 'yyyy-mm-dd',
        default: new Date(),
        setDefault: true,
        autoClose: true,
    });
    

    //Configure the select tag
    M.FormSelect.init(selectEl);
</script>


{% endblock %}

main_app/templates/music/index.html
{% extends 'base.html' %}
{% block content %}
<h1 class="page-title">My MusicMemories</h1>
<div class="cards">
    {% for i in music %}
        <div class="card">
            {% if i.photo_set.all %}
                <img class="card" src="{{ i.photo_set.all.first.url }}">
            {% else %}
                <img class="card" src="../../static/img/Music.png">
            {% endif %}
            <a href="{% url 'detail' i.id %}">
                <div class="card-content">
                    <span class="card-title">{{ i.date_created }}</span>
                    <p>Artist: {{ i.artist }}</p>
                    <p>Album: {{ i.album }}</p>
                    <p>Song: {{ i.song }}</p>
                    <p>Genre: {{ i.genre }}</p>
                </div>
            </a>
        </div>  
    {% endfor %}
</div>

{% endblock %}